const BCRYPTJS_SALT = 8;
const TOKEN_EXPIRES_AFTER_SECONDS = 3600*4;
const ACTIVATION_TOKEN_LENGTH = 32;
const AUTH_TOKEN_LENGTH = 64;

const PROFILE_PREFIX = 'avatar_'
const SHOP_PREFIX = 'shop_'
const DEFAULT_PROFILE_PIC = `${PROFILE_PREFIX}default.png`
const DEFAULT_SHOP_PIC = `${SHOP_PREFIX}default.png`

const ROLE_ADMIN = 'admin'
const ROLE_USER = 'user'

module.exports = {
	BCRYPTJS_SALT,
	TOKEN_EXPIRES_AFTER_SECONDS,
	ACTIVATION_TOKEN_LENGTH,

	PROFILE_PREFIX, DEFAULT_PROFILE_PIC,
	SHOP_PREFIX, DEFAULT_SHOP_PIC,

	ROLE_ADMIN, ROLE_USER,
}